### ISSUE TITLE
support for language_override

### ISSUE THREAD

**Issue by imod** [intercom/intercom-java#103]
## Version info
  - intercom-java version: 2.0.0

## Expected behavior
the Java SDK should support the user attribute 'language_override'

see also https://docs.intercom.io/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages#can-i-localize-the-intercom-sdks

while setting the attribute like this does add a new field with the expected data - the official attribute stays untouched...
`user.addCustomAttribute(CustomAttribute.newStringAttribute("language_override", "fr"));`

**Comment by bobjflong** [comment]
Hi @imod !

Your quoted example refers to Custom Attributes, which seems to be working fine for you.

The linked attribute refers to an option in the widget or frontend JavaScript SDK. `intercom-java` however wraps the [REST API](https://developers.intercom.io/reference#create-or-update-user). The `last_seen_ip` is the closest thing that will let you update location info.

Bob
