### ISSUE TITLE
ConversationPartCollection.getPageItems() does not exist but is in the readme and documentation

### ISSUE THREAD

**Issue by mlevyLI** [intercom/intercom-java#104]
## Version info
  - intercom-java version: 2.0.0 (latest)
  - Java version: 8

## Expected behavior
List<ConversationPart> list = parts.getPageItems();
## Actual behavior
Method ConversationPartCollection.getPageItems() does not exist
## Steps to reproduce
 1. Try to use
 2. Fail
 3. Cry

**Comment by mmartinic** [comment]
Usage example in docs was wrong. Updated to correct method name: `getPage()`, not `getPageItems()`.
