### ISSUE TITLE
Implement scroll API for users

### ISSUE THREAD

**Issue by Cimballi** [intercom/intercom-java#118]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io
## Version info
- intercom-java version: 2.1.0
- Java version: 1.8.x
## Expected behavior

The SDK should provide an implementation for the scroll API.
## Actual behavior

The SDK does not provide any implementation for the scroll API.
## Steps to reproduce
1. 
2. 
3.

**Comment by ThisIsManta** [comment]
Is this being planned? I would like to list ALL companies and got blocked by the error "page limit reached, please use scroll API" as well.

**Comment by lukas-gitl** [comment]
Same issue here... How are we supposed extract a listing through the api?

**Comment by mmartinic** [comment]
added in 2.2.5
https://github.com/intercom/intercom-java/releases/tag/2.2.5
