### ISSUE TITLE
Signed Up At resulted in Invalid Date

### ISSUE THREAD

**Issue by henryken** [intercom/intercom-java#126]
Setting signedUpAt doesn't set the date properly.

## Version info
  - intercom-java version: 2.2.1
  - Java version: 1.8

## Expected behavior
Date should be sent properly
## Actual behavior
Intercom shows "Invalid Date" on "Signed Up" date
## Steps to reproduce
 1. User.setSignedUpAt(System.currentTimeMillis())

**Comment by harkin** [comment]
Hi @henryken 

For this and other dates you'll need to provide the time as a [Unix timestamp](https://en.wikipedia.org/wiki/Unix_time) in seconds. From the steps to reproduce you're sending it in milliseconds and that'll get parsed to some year in the 40,000s. 

Something like `TimeUnit.MILLISECONDS.toSeconds(System.currentTimeMillis());` or your own preferred method of converting will make it an acceptable timestamp 👍

**Comment by dehora** [comment]
> User.setSignedUpAt(System.currentTimeMillis())

@henryken @harkin There's a method on the Intercom object for this that might help:  [Intercom.currentTimestamp()](https://github.com/intercom/intercom-java/blob/master/intercom-java/src/main/java/io/intercom/api/Intercom.java#L36)

**Comment by henryken** [comment]
Thanks for the pointers guys!
