### ISSUE TITLE
Conversation object is missing getTags() method

### ISSUE THREAD

**Issue by olegrise** [intercom/intercom-java#128]
## Version info
  - intercom-java version: 2.2.1
  - Java version: 7

## Expected behavior

According to the API https://developers.intercom.com/reference#conversation-model the Conversation object has `tags` attribute. Expected behavior for the Conversation object of the Java library is to have a method for getting `tags`.

## Actual behavior

Conversation object is missing `getTags()` method

**Comment by choran** [comment]
Hi @olegrise 
yeah, good call out, that is something that should be added. It is defo on the list.
Cant give an ETA unfortunately but will note it as feature which is needed. In the meantime will also keep an eye open in case anyone in the community submits a PR for this feature.
thanks again
Cathal

**Comment by thewheat** [comment]
Hi @olegrise , just wanted to give you a heads up that as of [version 2.2.11](https://github.com/intercom/intercom-java/pull/159) we now support listing tags on individual conversations 👍  

So I'm closing this issue as the changes have been merged and are available

**Comment by olegrise** [comment]
Awesome. Thanks a lot @choran !
