### ISSUE TITLE
getConversationPartCollection() creates recursion

### ISSUE THREAD

**Issue by jonasmonese** [intercom/intercom-java#137]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version: 2.2.3
  - Java version: 1.8.0_115

## Expected behavior
Get conversation parts

## Actual behavior
Endless loop polling intercom backend

## Steps to reproduce
 1. Conversation.find(conversation.getId()).getConversationPartCollection(); 
 2. Conversation does not have any parts

**Comment by mmartinic** [comment]
fixed in version 2.2.4
https://bintray.com/intercom/intercom-maven/intercom-java/2.2.4
