### ISSUE TITLE
language_override is not honored

### ISSUE THREAD

**Issue by esiqveland** [intercom/intercom-java#157]
## Version info
  - intercom-java version: 2.2.10
  - Java version: 1.8

## Expected behavior
Submitting an ISO language code using CustomAttribute `language_override` should override language for Intercom user:

```java
.addCustomAttribute(CustomAttribute.newStringAttribute("language_override", "en"))
```

## Actual behavior
The Custom Attribute `language_override` is not honored as the Language Override for the customer in the intercom UI.

## Steps to reproduce
 1. Add custom attribute language_override as string to User.
 2. Update `language_override` for User using `intercom.User.update(updatedUser)`.
 3. Observe Intercom UI that Language Override still says value is Nothing.

## Questions
I can not get the Language Override feature to work.
There might have been submitted invalid ISO language codes earlier in the process.
Will a single instance of invalid language code make the feature not work for all registered users?

**Comment by thewheat** [comment]
Hi @esiqveland thanks for raising this! 

I've taken a look at this and 
- "Language Override" is a [**standard attribute**](https://docs.intercom.com/intercom-s-key-features-explained/tracking-user-data/tracking-user-data-in-intercom#standard-data-attributes) 
- But it is not currently exposed in the [API](https://developers.intercom.io/reference) 

Based on this fact, there wouldn't be any code that we can add to the SDK to implement this feature, so I'm going to have to close this issue. We'll track this as an internal feature to see if we can upgrade our API to expose this and once it is there, feel free to reopen this issue 😄

Regarding your question about using an invalid code, I've tested this and specifying an invalid code 
- will not break things
- it will just not update the `language_override` value, so it will retain the previous valid record

**User details showing `language_override` standard and custom attributes**
![image](https://user-images.githubusercontent.com/892961/32401148-64b1109a-c144-11e7-8ca4-7c8f5c3b87c4.png)

**No `language_override` standard attribute in API output**
![image](https://user-images.githubusercontent.com/892961/32401140-52297d0e-c144-11e7-9ba9-46154ce0298b.png)

**Trying to update `language_override` standard attribute via API without success**
![image](https://user-images.githubusercontent.com/892961/32401041-04d202fc-c143-11e7-834a-4d06001555db.png)

**Comment by esiqveland** [comment]
Thank you for quick response. I am sure I read somewhere in the docs to send the language_override as a custom attribute, but I can't find it now. :(

Is there another recommended way to set a customer's chosen language?

**Comment by harkin** [comment]
This might be the article you found: [Intercom Messenger localisation](https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages). The `language_override` attribute can be supplied to the Messenger to force the Messenger UI to display in a particular language. 

For the public API though that doesn't really make sense (nothing gets displayed to the user from the public API!). What's your use case for setting it @esiqveland?

**Comment by tsm91** [comment]
@harkin any update on this? I ran into the very same situation. By specifying the `language_override` in the `boot` method I would expect to:
  - see your Intercom client interface on the specified language
  - filter audience in Auto Messages by this custom attribute

At the moment none of the above is true.

```js
Intercom('boot', {
   'app_id': '....',
  'language_override': 'de' // << ISO 639-1 two-letter code
});
```

<img width="401" alt="screen shot 2018-07-10 at 23 15 21" src="https://user-images.githubusercontent.com/4459551/42538313-ea85b61e-8497-11e8-9cce-23120744bfb9.png">

<img width="292" alt="screen shot 2018-07-10 at 23 18 56" src="https://user-images.githubusercontent.com/4459551/42538315-ee5d87a8-8497-11e8-90ef-b98dd09a26f3.png">

**Comment by thewheat** [comment]
@tsm91 specifying `language_override` while booting the Intercom Messenger should definitely be supported as per https://docs.intercom.com/configure-intercom-for-your-product-or-site/customize-the-intercom-messenger/localize-intercom-to-work-with-multiple-languages#send-messages-to-users-in-their-language

That is more to do with our Javascript messenger as opposed to the API and Java library though. I'd recommend getting in touch with our support team via the Intercom messenger [in your app](https://app.intercom.com/) / emailing team@intercom.com to help investigate the issue further 👍 

Note that Intercom Messenger language will only change language if you have added it as a supported language in [your messenger settings](https://app.intercom.io/a/apps/_/messenger)

![image](https://user-images.githubusercontent.com/892961/42636717-0fd774fe-861c-11e8-9f54-e2a89aae79b2.png)
