### ISSUE TITLE
Set avatar

### ISSUE THREAD

**Issue by JRobertson90** [intercom/intercom-java#162]
## Version info
  - intercom-java version: 2.2.11
  - Java version: 1.8.0_131

## Expected behavior
Ability to set avatar

## Actual behavior
There is no setter method in the User object for the avatar. 
Is this by design?

**Comment by thewheat** [comment]
Thanks for raising this up @JRobertson90 !

Looks like we just don't have that feature yet in the current version. But I can confirm that it is possible to update the avatar via the API so we can definitely add it in 👍 

Would this be something you're keen to work on? If not that's ok, we can work on it internally 😄 

**Example of it working**
![image](https://user-images.githubusercontent.com/892961/33164633-aa429b4a-d06e-11e7-8b2e-631246a4119e.png)


**Sample code to update avatar**
`POST` to https://api.intercom.io/users
```
{
  "user_id": "13",
  "avatar": {
    "type": "avatar",
    "image_url": "https://marketing.intercomassets.com/assets/educate_new/early-stage-b091b7b683224dfdfe0a61e31bc02bfc93ebc430a4557be120b1a05da0cabb43.png"
  }	
}
```

**Comment by JRobertson90** [comment]
I think that's something I can do. I'll probably send you a PR sometime this week.

**Comment by thewheat** [comment]
Fantastic @JRobertson90 😄  Will be waiting 👍

**Comment by thewheat** [comment]
@JRobertson90 I'm looking to close up this issue in the new year so let me know if you're good to continue work on this otherwise I'll just create a new PR next year when I'm back so that we can get this added to the library 👍

**Comment by thewheat** [comment]
Just a heads up, that I've added a PR for this in https://github.com/intercom/intercom-java/pull/174 👍

**Comment by JRobertson90** [comment]
Thank you, @thewheat, I got distracted and forgot about this.

**Comment by thewheat** [comment]
Not a problem @JRobertson90 😄  It is still a pull request yet to be merged but it will be coming soon enough! 👍

**Comment by antonholmquist** [comment]
@thewheat If it's possible to set avatar through the API, why is it not in the documentation?

This has also been discussed here: https://github.com/intercom/intercom-ruby/issues/138

**Comment by thewheat** [comment]
@antonholmquist yes it is possible to set avatar via the API 👍  

I do see that the documentation isn't clear on what fields can be updated and which are not though 
- There is mention that some data is read only
> Social data is read only and can not be updated via the API.
> Location data is read only and can not be updated via the API.
- But attributes like `session_count` is not something you can update and we don't specifically mention that 

I'll let the team know about this and see if we can get some better documentation 😄
