### ISSUE TITLE
The conversationMessage object doesn't return a message_id

### ISSUE THREAD

**Issue by theandrewykim** [intercom/intercom-java#176]
## Expected behavior

https://github.com/intercom/intercom-java/blob/master/intercom-java/src/main/java/io/intercom/api/ConversationMessage.java should return a message_id in order to complete the behavior detailed in our developer docs: 

```
Note that since creating an admin-initiated conversation hits the /messages endpoint, the response contains a message object rather than a conversation object. As a result you will not see the conversation ID in the returned message object. You may, however, retrieve the customers's conversations and iterate over them looking for the message_id value.


```
## Actual behavior

Right now this isn't possible because we don't have any information linking a conversation and it's starting message.

**Comment by frankreno** [comment]
Any idea on when this can be fixed? Blocker for us at the moment.

**Comment by thewheat** [comment]
Hey @frankreno I've made a PR here https://github.com/intercom/intercom-java/pull/177 with the changes that are needed for this and added a couple more attributes 😄  

Will try get it merged as soon as possible 👍

**Comment by thewheat** [comment]
@frankreno the changes have been merged so do give the latest code base a try and let us know how it goes

**Comment by frankreno** [comment]
@thewheat thank's much!
