### ISSUE TITLE
Provide setter for `industry` and `website` for `Company`

### ISSUE THREAD

**Issue by TobseF** [intercom/intercom-java#179]
The Java API don't have `setIndustry(..)` or `setWebsite(..)` for the `Company` obejct. Otherwise there is no way to set these **default** values with the Java API.

## Version info
  - intercom-java version: _2.3.1_.
  - Java version: _9+181_

## Expected behavior

![2018-01-30_13h58_35](https://user-images.githubusercontent.com/1190109/35567855-c47d6642-05c6-11e8-94d2-45b0aaee3ab6.png)

The `io.intercom.api.Company` class should provide setter for `website` and `industry`.

## Actual behavior
I can only set these fields (`website` and `industry` like mentioned in the [company API doc](https://developers.intercom.com/v2.0/reference#create-or-update-company)) as custom string attributes. But then their not present on the company preview tab.

**Comment by thewheat** [comment]
@TobseF thanks for creating the issue 😄 

Looks like there are 3 company standard attributes not being defined in the code
![image](https://user-images.githubusercontent.com/892961/35598523-eb9c7216-065e-11e8-8b71-d2c6a5fef1fd.png)

I've got the main setters and getters code here https://github.com/intercom/intercom-java/tree/timlim/company-setters but will add some tests before making a full pull request 👍

**Comment by choran** [comment]
I will close this since the PR has been merged.
We will do a new release shortly
