### ISSUE TITLE
Unable to tag contacts through the Java api 

### ISSUE THREAD

**Issue by blong824** [intercom/intercom-java#184]
## Version info
  - intercom-java version: 2.2.6
  - Java version: 1.8

## Expected behavior
I am expecting to call Tag.tag(tag, contact); and be able to tag a contact through the java api. 

## Actual behavior
The java api only allows users or companies as the second parameter. 

## Steps to reproduce
 1.  Tag.tag(tag, contact) will not compile

**Comment by thewheat** [comment]
Thanks for raising this @blong824 ! 👍  You're correct that the current SDK doesn't support tagging by a Contact object right now but there is a workaround by creating a User object with the same ID as the Contact

From the docs https://developers.intercom.com/reference#tag-or-untag-users-companies-leads-contacts

> Contacts/Leads can be tagged by supplying a `users` array. The array contains objects identifying leads by their `id` fields.

So something like that shown below will work

```
   // get a Tag object
   Tag tag = new Tag().setName("alliance");
   tag = Tag.create(tag);
    
   // get a Contact object and "convert" it to a User object
   Contact contact = Contact.findByID("5a8b7f19e0dd65126722b55c");
   User contactAsUser = new User();
   contactAsUser .setId(contact.getID());

   // Tag the contact via a User object
   Tag.tag(tag, contactAsUser);
```

A quick look at the code, to enable support for Contacts looks like we'd need to replicate these 2 user code blocks and add some tests
- https://github.com/intercom/intercom-java/blob/f50c869194eac5d4fc047e08634b99c14334e88b/intercom-java/src/main/java/io/intercom/api/Tag.java#L33-L36
- https://github.com/intercom/intercom-java/blob/f50c869194eac5d4fc047e08634b99c14334e88b/intercom-java/src/main/java/io/intercom/api/Tag.java#L66-L98

Is that something you'd been keen on doing? 😄  If not, that isn't a problem and we can get to it 👍

**Comment by thewheat** [comment]
Just a heads up that I'll be working on making a PR for this enhancement this week

**Comment by thewheat** [comment]
PR created at https://github.com/intercom/intercom-java/pull/191/ 👍

**Comment by alkaphreak** [comment]
On which version does this PR is present ? 
I got this problem today. (I'm in 2.2.12)
