### ISSUE TITLE
"Requested resource doesn't exist" when hitting scroll param

### ISSUE THREAD

**Issue by jonnyom** [intercom/intercom-java#185]
Hitting the `scroll()` method on the User object returns a NotFoundException.

```
 public static List<User> scrollUsers(){
        ScrollableUserCollection usersScroll = User.scroll();
        List<User> users = new ArrayList<User>();
        while(usersScroll.scroll()!=null){
            users = usersScroll.getPage();
            usersScroll = usersScroll.scroll();
        }
        return users;
    }

    public static void main( String[] args )
    {
        Intercom.setToken(ACCESS_TOKEN);

        List<User> users = scrollUsers();
        for(User user: users){
            System.out.println(user.getId());
        }

    }
```

This code returns the following 👇
```
Exception in thread "main" io.intercom.api.NotFoundException: The requested resource does not exist; check your path and try again
	at io.intercom.api.HttpClient.throwException(HttpClient.java:208)
	at io.intercom.api.HttpClient.handleError(HttpClient.java:169)
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:155)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:110)
	at io.intercom.api.HttpClient.get(HttpClient.java:86)
	at io.intercom.api.HttpClient.get(HttpClient.java:82)
	at io.intercom.api.DataResource.scroll(DataResource.java:75)
	at io.intercom.api.User.scroll(User.java:80)
	at ApiTest.scrollUsers(ApiTest.java:55)
	at ApiTest.main(ApiTest.java:79)
```
Where `ApiTest.java:55` corresponds to `ScrollableUserCollection usersScroll = User.scroll();`

## Version info
  - intercom-java version: 2.3.2

## Steps to reproduce
 1. Create a new scroll
 2. Try to hit the scroll

## Logs
Scroll isn't hitting the `/users` endpoint at all as it's not being reached

**Comment by mkaratkou** [comment]
<img width="1587" alt="intercom-sc" src="https://user-images.githubusercontent.com/8901366/36797252-8922dede-1cb8-11e8-9965-c96516bb21d9.png">
That's results of my debugging. 
io.intercom.api.HttpClient.executeHttpMethod() method, line 112

wrong URI (duplicated slash): https://api.intercom.io//users%2Fscroll

**Comment by mkaratkou** [comment]
the same issue encountered for 2.2.11 version

<img width="1528" alt="intercom-sc-2 2 11" src="https://user-images.githubusercontent.com/8901366/36798485-d556fc4c-1cbb-11e8-9004-d4f92e70eb3f.png">

there's a guess that sdk version should be upgraded.
Reproduced on java 1.8:
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
Mac OS High Sierra 10.13.3

Did anyone reproduced that besides me???

**Comment by rcauligi** [comment]
URIBuilder encodes "*/scroll"  to "*%2Fscroll". This used to work until last week. Poking around, I found that perhaps intercom changed the server side configuration to disallow %2F in the URL
https://stackoverflow.com/questions/3235219/urlencoded-forward-slash-is-breaking-url
specifically, AllowEncodedSlashes directive.
I found the duplicated slash is not a problem, but %2F is. I can reproduce this error in Postman with
https://api.intercom.io/users%2Fscroll with the following response
{
    "errors": [
        {
            "code": "not_found",
            "message": "The requested resource does not exist; check your path and try again"
        }
    ],
    "type": "error.list"
}

**Comment by mkaratkou** [comment]
Hey, guys. Is there any updates?

**Comment by mkaratkou** [comment]
Ping

**Comment by thewheat** [comment]
Thanks for the investigation @rcauligi and @mkaratkou 

I've created a pull request https://github.com/intercom/intercom-java/pull/186 that addresses this problem. Will try get this approved as soon as possible with a new release 👍 

Seems that incorrect encoding has been going on from some time and it would have been a bug for our API to accept the incorrect encoding. So the PR I created was to fix this library to call the correct endpoint

**Comment by mkaratkou** [comment]
Hey @choran and @rcauligi,

the 2.3.3 version is not uploaded into maven repository - http://jcenter.bintray.com/io/intercom/intercom-java/

Please upload the fixes. We really need them.

**Comment by thewheat** [comment]
@mkaratkou we're having a couple of issues publishing the latest release to bintray but we're working our best to publish. 

Is it possible to utilise the updated source https://github.com/intercom/intercom-java to use in your project in the mean time to unblock any work for you?
