### ISSUE TITLE
Wrong version name

### ISSUE THREAD

**Issue by w201** [intercom/intercom-java#188]
![default](https://user-images.githubusercontent.com/2488785/37093102-6c910b8c-220e-11e8-8084-b17c2a42d9d6.png)

**Comment by thewheat** [comment]
@w201 we're having a couple of issues publishing the final release to bintray, we're trying to fix it up as soon as possible 👍 

If you need the latest codebase you can always compile the latest code from the source for the time
 being 😄

**Comment by w201** [comment]
I think the the best way is change in readme link to the REAL latest version.
`compile 'io.intercom:intercom-java:2.3.**2**'`

**Comment by choran** [comment]
Hi,
Sorry for the delay here, we encountered a number of problems here with the last release which meant that we were stuck in version limbo for a while.
We were reaching out the a number of people to try and resolve this but have eventually identified a work around. So the latest version should be up to date and we should not run into this issue again in future as we have a "plan B' in place to ensure there is no sure delay again if this similar issue re-occurs

I will close this issue for now but feel free to let me know if you see any issue with this version
