### ISSUE TITLE
Company.delete method listed in our JAVA API, but we don't support company deletion via the API

### ISSUE THREAD

**Issue by Aslonski** [intercom/intercom-java#207]
**[Link to the method in our JAVA API](https://github.com/intercom/intercom-java/blob/master/intercom-java/src/main/java/io/intercom/api/Company.java#L52)**

Based on our **[API DOCS](https://developers.intercom.com/reference#delete-a-company)** we don't support that functionality.
![image](https://user-images.githubusercontent.com/16740843/42528530-5ac2fe66-8441-11e8-86ef-36f5734e2809.png)

We need to either update the docs, or to add the functionality to the API.

**Comment by thewheat** [comment]
There is no valid API endpoint for this so we'd need to change the SDK to remove this reference

![image](https://user-images.githubusercontent.com/892961/42559946-14b8948e-8528-11e8-9f74-586c5006dcae.png)

Possibly it was added as part of standard code and there was no actual endpoint here

**Comment by SeanHealy33** [comment]
@choran any thoughts on this bug? It looks like we added this functionality to the api wrapper long ago but the api endpoint was never built.

**Comment by thewheat** [comment]
I've merged https://github.com/intercom/intercom-java/pull/211 which removes this endpoint in the SDK as the API functionality doesn't at this point in time. 

Happy to revisit this if we do end up implementing a deletion option though 👍
