### ISSUE TITLE
No interface for Visitors?

### ISSUE THREAD

**Issue by ronaldjeremy** [intercom/intercom-java#208]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version:2.4.0
  - Java version:1.8

## Expected behavior
Able to convert a Visitor to a Contact
## Actual behavior
Unable to do that
## Steps to reproduce
 1. recieve a visitor id cookie
 2. try to convert a Visitor to a Contact
 3. unable to do that

**Comment by thewheat** [comment]
Thanks for the issue @ronaldjeremy. I've marked this as an enhancement to be created 👍 

We'll be happy to accept any pull requests implementing this at the moment as I don't have the current bandwidth to tackle this immediately. 

If you need this feature now, you could look into making a raw API call. I created a [sample repository that shows how you can do a manual API call](https://github.com/intercom-archive/intercom-testing-api/blob/master/java/raw-api-calls-commandline-gradle/src/main/java/main/Main.java) if you need a template 😄

**Comment by thewheat** [comment]
Picking this up to work on this in this branch https://github.com/intercom/intercom-java/tree/timlim/add-visitors 👍

**Comment by choran** [comment]
This is now merged, will do a release shortly so will close this now
