### ISSUE TITLE
API fields missing

### ISSUE THREAD

**Issue by justas79** [intercom/intercom-java#220]
Hi,

I'm using version: io.intercom:intercom-java:2.4.0
I do not see these attributes in the io.intercom.api.Company class:
- last_contacted_at
- last_request_at

I can calculate last_request_at by aggregateing data from all users of company. 
How could I calculate last_contacted_at without going through all conversations for all users? 

Thanks!

**Comment by thewheat** [comment]
Hi @justas79 thanks for the question!

`last_contacted_at` isn't something currently in our [Company model](https://developers.intercom.com/intercom-api-reference/reference#company-model) nor [User model](https://developers.intercom.com/intercom-api-reference/reference#user-model)

From the web interface it should be attached to the User model. 

![image](https://user-images.githubusercontent.com/892961/44128011-f3518074-a072-11e8-835d-044e5befd787.png)

But we do not expose it in the API right now

![image](https://user-images.githubusercontent.com/892961/44128110-978363a6-a073-11e8-84ec-b314b6ecd005.png)

As this would require an API upgrade, it is not something we can fix within this library itself. I'll mark this internally as a feature request and once it gets implemented we can revisit adding that attribute to the User class 👍 

* * * 

`last_request_at` is part of our current Company model and will be added in this PR https://github.com/intercom/intercom-java/pull/183  😄 

![image](https://user-images.githubusercontent.com/892961/44127955-9c3f8056-a072-11e8-8ec8-01d1876ca78f.png)

* * *

> How could I calculate last_contacted_at without going through all conversations for all users?

For now via the API the best way would be to list conversations attached to the user and see which is the latest conversation. If you have a particular need or use case that you need to solve, do feel free to get in touch with us via the Intercom messenger on https://intercom.com or email us at team@intercom.com and we'd be happy to help discuss any possible options!

**Comment by justas79** [comment]
Thanks for details answer!

**Comment by thewheat** [comment]
You're most welcome @justas79 . Will let you know when we've merged the PR and released a new version!
