### ISSUE TITLE
intercom 2.5.0 release not on maven central

### ISSUE THREAD

**Issue by pjfanning** [intercom/intercom-java#221]
https://mvnrepository.com/artifact/io.intercom/intercom-java

Latest is v2.4.0.

The github README.md and github releases list a 2.5.0 release.

**Comment by thewheat** [comment]
Thanks for the mentioning this @pjfanning . Seems that part of our deployment pipeline is stuck preventing this from being released. Will try get the team on this as soon as possible to get this fully fixed 👍

**Comment by pjfanning** [comment]
I had a look on bintray and it seems like the 2.5.0 release is not fully published.
I'm guessing but you have quite an old version of com.jfrog.bintray.gradle:gradle-bintray-plugin (0.6) but upgraded gradle core version recently. It could be that 0.6 does not work properly with the latest version of gradle.

**Comment by thewheat** [comment]
@pjfanning we've managed to get the deployment fixed. Version 2.5.1 is now released 🎉 

On Bintray
![image](https://user-images.githubusercontent.com/892961/44885406-433e8000-acf3-11e8-9b84-4059439982b3.png)

In Maven Repository
- this does list under `JCenter` as opposed to `Spring Lib Release` like the others. Will check with the team on that to see if we want to keep things in one place for consistency or if we're starting new ones with JCenter
![image](https://user-images.githubusercontent.com/892961/44885365-19855900-acf3-11e8-8e4a-28da509bc26a.png)
