### ISSUE TITLE
setApiKey should be removed from Intercom API

### ISSUE THREAD

**Issue by tabiul** [intercom/intercom-java#226]
## Version info
  - intercom-java version: 2.5.2
  - Java version: 7

## Expected behavior
Since API Key usage is no longer supported as such I believe it should be removed from the class `Intercom` 

## Actual behavior

https://github.com/intercom/intercom-java/blob/master/intercom-java/src/main/java/io/intercom/api/Intercom.java#L102  exists when the feature is not supported

## Steps to reproduce
NA

**Comment by thewheat** [comment]
@tabiul thanks for this issue 👏  This definitely makes sense. Let me bring this up with the team to ensure that it isn't being used in other ways but I'm leaning on the removal of it 👍

**Comment by thewheat** [comment]
Yup looks like we can get going removing token usage from the library. Is this something you'd be interested in contributing to @tabiul ? 😄  Happy to work with you on it if needed

**Comment by thewheat** [comment]
I've created pull request here https://github.com/intercom/intercom-java/pull/230 👍

**Comment by choran** [comment]
This is now merged and will be release shortly, hopefully later this week. We are just trying to  get a few more PRs merged and then do the release
