### ISSUE TITLE
CompanyUpdateBuilder.java contains function to update session_count, which isn't possible

### ISSUE THREAD

**Issue by Schwarzglut** [intercom/intercom-java#231]
CompanyUpdateBuilder.java contains a function to update the session count of a company, we don't allow the updating of session count so this is throwing a "bad 'session_count' parameter" when trying to update a company.

Line of code: 
https://github.com/intercom/intercom-java/blob/5586abb6f6f5fa0594f24ff62dde86b91572b972/intercom-java/src/main/java/io/intercom/api/CompanyUpdateBuilder.java#L56

## Version info
  - intercom-java version: 2.5.2
  - Java version:

## Expected behavior

You can't update the session count of a user or company. 

## Actual behavior

We're allowing the attempt to update the session count of a company

## Steps to reproduce
 1. Create a user
 2. Attempt to add a company to that user (user.addCompany(company);)
 3. See in your logs the "bad 'session_count' parameter" issue

**Comment by thewheat** [comment]
PR to address this created here https://github.com/intercom/intercom-java/pull/233 👍

**Comment by choran** [comment]
Merged pr so closing issue and will do a release shortly
