### ISSUE TITLE
HttpClient createAuthorizationHeaders TOKEN

### ISSUE THREAD

**Issue by RafaelCavazza** [intercom/intercom-java#238]
Hi,

I'm using the java sdk and got an error when replying a conversation.

Inspecting the source code showed me that the Authorization header was not using the Bearer token.

I've downloaded the source code and changed it my project.

Is this the designed behaviour?

The code from the 2.7.0 tag
![image](https://user-images.githubusercontent.com/8078357/47523300-1aa7b200-d86e-11e8-8767-f480c380b6cc.png)

The code I downloaded and changed in my project.
![image](https://user-images.githubusercontent.com/8078357/47523063-889fa980-d86d-11e8-9903-f87fd9cf8218.png)

## Version info
  - intercom-java version: 2.7
  - Java version: 1.8

**Comment by thewheat** [comment]
Hmmm I'm not able to replicate this @RafaelCavazza  

Would you mind sharing the code you're using that throws the error? That may help us replicate it 👍 

Below is a test I did and it worked successfully

```
        Intercom.setToken(TOKEN);
        Admin admin = new Admin().setId("248698");
        AdminReply adminReply = new AdminReply(admin);
        adminReply.setBody("These apples are healthsome 1 2 3");
        Conversation.reply("19223366014", adminReply);
```
![image](https://user-images.githubusercontent.com/892961/47562825-6469c880-d952-11e8-8da2-c05d2523f81b.png)


Would you mind sharing the code that you used?

**Comment by thewheat** [comment]
I'm going to close out this issue as I can't replicate things but feel free to reopen @RafaelCavazza if you can provide some replication steps for us to see the error 👍
