### ISSUE TITLE
No way to bulk create/update users 

### ISSUE THREAD

**Issue by christianharrington** [intercom/intercom-java#24]
It would be great if it was possible to bulk create/update users. Currently the [API docs](http://doc.intercom.io/api/?java#bulk-user-creation) say this is not exposed in the Java client. Is there a reason for this? If not, this would be a very helpful addition.

**Comment by christianekstrand** [comment]
We at YouCruit have forked intercom-java (https://github.com/YouCruit/intercom-java) and added some bulk create methods that we needed to import our existing userbase. It is a bit "quick'n'dirty", but it did work for us...

**Comment by johanstenberg92** [comment]
@dehora I would also like to see a bulk insert on users, this one is quite annoying: "Exception More than 500 requests received in 1 minute"

**Comment by bscanlan** [comment]
https://github.com/intercom/intercom-java/commit/63021bd6270df8ec60bee1c3469bcc859688aa86 resolved this :)
