### ISSUE TITLE
api logout error

### ISSUE THREAD

**Issue by tommyhh** [intercom/intercom-java#255]
Please use the following template to submit your issue. Following this template will allow us to quickly investigate and help you with your issue. Please be aware that issues which do not conform to this template may be closed.

For feature requests please contact us at team@intercom.io

## Version info
  - intercom-java version:5.2.1
  - Java version:

## Expected behavior
when i use logout api ,
## Actual behavior
Api call failed: registered user changed while this request was in flight
## Steps to reproduce
 1. 
 2. 
 3.

**Comment by lloydliyu** [comment]
Hey @tommyhh :wave:

Can you add further details here? I'm not to sure what you mean by logout API. Are you by any chance referring to our intercom-android SDK at all?

Closing this out pending more details.
