### ISSUE TITLE
scroll parameter not found

### ISSUE THREAD

**Issue by panser** [intercom/intercom-java#261]
have the issue
```
        io.intercom.api.NotFoundException: scroll parameter not found
	at io.intercom.api.HttpClient.throwException(HttpClient.java:207)
	at io.intercom.api.HttpClient.handleError(HttpClient.java:169)
	at io.intercom.api.HttpClient.runRequest(HttpClient.java:155)
	at io.intercom.api.HttpClient.executeHttpMethod(HttpClient.java:110)
	at io.intercom.api.HttpClient.get(HttpClient.java:86)
	at io.intercom.api.HttpClient.get(HttpClient.java:82)
	at io.intercom.api.DataResource.scroll(DataResource.java:75)
	at io.intercom.api.ScrollableUserCollection.scroll(ScrollableUserCollection.java:11)

```

use
`
compile group: 'io.intercom', name: 'intercom-java', version: '2.8.0'
`

**Comment by LunaDVP** [comment]
Same issue here, version 2.8.0. Any solution?

**Comment by Findocode** [comment]
I found the answer on my question in their blog https://developerblog.intercom.com/a-new-way-to-list-large-numbers-of-users-175579a24572#.u2nsmk1pf
```
Each app can only have 1 scroll open at a time.
You’ll get an error message if you try to have more than one open per app.

Plus, if the scroll isn’t used for 1 minute, 
it expires and calls with that scroll param will fail.
```

so `ScrollParameter NotFound` - it's 2nd limitation from this list. My solution was rewrite code that not used scroll longer then 1 minute

**Comment by panser** [comment]
I found the answer on my question in their blog https://developerblog.intercom.com/a-new-way-to-list-large-numbers-of-users-175579a24572#.u2nsmk1pf
```
Each app can only have 1 scroll open at a time.
You’ll get an error message if you try to have more than one open per app.

Plus, if the scroll isn’t used for 1 minute, 
it expires and calls with that scroll param will fail.
```

so `ScrollParameter NotFound` - it's 2nd limitation from this list. My solution was rewrite code that not used scroll longer then 1 minute

**Comment by LunaDVP** [comment]
OK. Thanks for sharing. I think for us, It's more about the function doesn't know when is the last scroll. We just had to put try/catch exception around it and ignore the parameter not found exception.

**Comment by lloydliyu** [comment]
Closing this out as this appears more to do with the API and its limitations rather than the SDK itself. 

@LunaDVP regarding your experience, If you're still running into issues with this, I'd recommend you to ask that question in the community forum or in the API reference via the Intercom messenger. That way you'll find the people with the right context and we'll be able to register a feature request if that's not possible at the moment.
