### ISSUE TITLE
Missing: conversation 'customer_first_reply'

### ISSUE THREAD

**Issue by RafaelCavazza** [intercom/intercom-java#262]
Hi,

The 'Conversation' class is missing the 'customer_first_reply' property.

Is there a way to get the property value?

"customer_first_reply": {
        "created_at": 1572027728,
        "type": "conversation",
        "url": "xxx/2502959-teste"
    },

## Version info
  - intercom-java version:2.8.0
  - Java version:8

**Comment by alexshultsg** [comment]
@RafaelCavazza  Please, review https://github.com/intercom/intercom-java/pull/263
Thank you

**Comment by alexshultsg** [comment]
Fixed with 2.8.1

**Comment by RafaelCavazza** [comment]
Thank you!
