### ISSUE TITLE
HTTP Requests should retry on 503 (maybe 429)

### ISSUE THREAD

**Issue by marcomorain** [intercom/intercom-java#29]
We have a custom integration with Intercom that hits the `/users/` API, and we have been getting some 503 errors recently, which the Intercom support team say are temporary global rate limits akin to Amazon S3's use of "503 slow down". We also get some (documented) `429`s when we hit the API too frequently.

I want to replace our integration with your Java client, rather than having to deal with retrying myself, but I notice that the client will throw an exception when your API returns a `503`, rather than retrying with exponential back-off.

Backing off when a `429` is received would be handy too (there should be enough information in the `429` response header to reschedule the API call).

**Comment by bscanlan** [comment]
Just annotating the issue with relevant materials:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/retry/RetryPolicy.html

http://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by choran** [comment]
Hi @marcomorain 
We are just reviewing older issues that may no longer be active. In most of our SDKs we do not have specific retry code for different errors. Sometimes it can be better to have a light weight SDK where customers themselves can choose how to react to different errors. But it is something  that we have talked to different customers about i.e. how best to handle certain errors such as rate limiting.
We have made many changes to thing such as rate limiting in the meantime so for now I will close this issue. However, if you still feel this is an issue or would like to add more info then feel free to re-open an we will be happy to discuss further.
Thanks and sorry for the delay in responding
Cathal
