### ISSUE TITLE
Bintray deprecation - move artifacts elsewhere

### ISSUE THREAD

**Issue by edeak** [intercom/intercom-java#290]
## Version info
  - intercom-java version: 2.8.0
  - Java version: N/A

According to this article on JFrog (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) artifacts might have to be uploaded to a public repository, such as maven central.

**Comment by Alien2150** [comment]
Any news on it? Think the deadline is 1st of May: 

```
Bintray services will no longer be available. GoCenter, and ChartCenter services will no longer be available to non-Artifactory clients. (ConanCenter is not affected).
```

**Comment by edeak** [comment]
https://search.maven.org/search?q=g:io.intercom
