### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by rasharab** [intercom/intercom-java#305]
I've noticed quite a few noteable issues without any response that seems to indicate that support for this library has stopped.
Can someone on the Intercom team indicate otherwise?

**Comment by emanuelnlopez** [comment]
so, is it dead @rasharab? have you received any confirmation?

**Comment by cies** [comment]
I'm also curious... There seems to be very little activity here.

**Comment by cies** [comment]
@rasharab why did you close this? please reopen so this issue gets the visibility it deserves.

**Comment by mertant** [comment]
~3 years later, there is now some new activity in the repo:

- https://github.com/intercom/intercom-java/releases/tag/3.0.0-alpha0
- https://github.com/intercom/intercom-java/releases/tag/3.0.0-alpha1
