### ISSUE TITLE
Crashes when user has invalid social media url

### ISSUE THREAD

**Issue by johanstenberg92** [intercom/intercom-java#33]
This one hit me today in production:

 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@51c238c1; line: 1, column: 28384] (through reference chain: io.intercom.api.UserCollection["users"]->java.util.ArrayList[23]->io.intercom.api.User["social_profiles"]->io.intercom.api.SocialProfileCollection["social_profiles"]->java.util.ArrayList[0]->io.intercom.api.SocialProfile["url"])]
13:47:57.453 [pool-8-thread-1] ERROR shortcut.customers.package$ - Thread exception in intercom cron: Local exception calling [https://api.intercom.io/users?per_page=50&page=468]. Check connectivity and settings. [Can not construct instance of java.net.URI from String value 'http://www.myspace.com/alexandra thorvall': not a valid textual representationproblem: Illegal character in path at index 32: http://www.myspace.com/alexandra thorvall

Apparently you don't url encode urls or something.

How do I fix this?

**Comment by dehora** [comment]
@johanstenberg92 thanks for reporting this. Will take a look as soon as I can.

**Comment by johanstenberg92** [comment]
Any quick fix?

**Comment by dehora** [comment]
Checked, and it's data from an upstream service that's being passed along. I might be able to patch the marshaller to encode the uris first.

**Comment by johanstenberg92** [comment]
Ok, when will you have a new version out? Could you comment here when it's done?

**Comment by dehora** [comment]
Will do, let's say in the next 24h

**Comment by johanstenberg92** [comment]
Cheers, thanks for the quick response!

**Comment by dehora** [comment]
@johanstenberg92 I've pushed a 1.0.3 version that dealt with whitespace in profile data for me locally. Hope that helps, let me know if it doesn't.

**Comment by johanstenberg92** [comment]
The same bug didn't happen, but another bug showed itself, I'll post a new issue.
