### ISSUE TITLE
Crashes when bulk fetching users on social media links

### ISSUE THREAD

**Issue by johanstenberg92** [intercom/intercom-java#35]
Another social media bug:

Thread exception in intercom cron: Local exception calling [https://api.intercom.io/users?per_page=50&page=414]. Check connectivity and
 settings. [no protocol: dusting.tumblr.com (through reference chain: io.intercom.api.UserCollection["users"]->java.util.ArrayList[45]->io.intercom.api.User["social_profiles"]->io.intercom.api.SocialProf
ileCollection["social_profiles"]->java.util.ArrayList[4])]

This is the second bug on a short time I found, the other bug was also on parsing these URLs.

Could you *please* just parse the URL as a string, and then create something like a getURL or let the user of the API get it? Since I haven't added these links to my users, intercom has. Or just make it optional to fetch the social media profiles?

**Comment by johanstenberg92** [comment]
Any update on this?

**Comment by johanstenberg92** [comment]
Bump again

**Comment by dehora** [comment]
sorry for not getting to this sooner johanstenberg92 :( I'll take a look in the next 12h

**Comment by johanstenberg92** [comment]
@dehora Status on this one?

**Comment by dehora** [comment]
@johanstenberg92 I had a look and it's been introduced as a side effect of the last fix made to social links (not handling a case when the url is parsed and escaped). I'll get a pr together as soon as I can.
