### ISSUE TITLE
io.intercom.api.ClientException: bad 'type' parameter

### ISSUE THREAD

**Issue by gemmell** [intercom/intercom-java#45]
Using 1.0.7
```
Intercom.setAppID(appId);
Intercom.setApiKey(apiKey);

User user = new User();
user.setEmail(email);  //where email is my email address.
User.create(user);
```
Gives me
`io.intercom.api.ClientException: bad 'type' parameter`

I stepped through the code, sure enough, the server is sending back a 400 with bad 'type' parameter as the message...

**Comment by gemmell** [comment]
Possibly related, this is not throwing any exceptions, but also not actually creating a company:
```
        Company company = new Company();
        company.setName(orgName);
        company.setCompanyID(orgId);
        company.setPlan(new Company.Plan("Beta"));
        Company createdCompany = Company.create(company);
```

**Comment by dehora** [comment]
@gemmell for companies, the server has a limitation currently where it doesn't list the company until a user has been added to it (the company will have been created).

There's a pr in the works for the type field bug. It should be available shortly.

**Comment by dehora** [comment]
@gemmell there's a 1.0.8 version now that has a fix for the update bug, let me know if that doesn't work for you.
