### ISSUE TITLE
Can't set the LocationData of a User from Api

### ISSUE THREAD

**Issue by TFinnT** [intercom/intercom-java#50]
I'm looking for creating users from the api and set his location.

I've seen the location_data property in the User Object and a getter but i can't find a setter for this property.

Is there any restriction for this property or just a lost setter function?

Thanks in advance.

**Comment by dehora** [comment]
@TFinnT the `location_data` object is computed by Intercom and at the moment it can't be updated directly through the API. Probably the best option here would to set the `last_seen_ip` for the user.

**Comment by TFinnT** [comment]
So, If I give intercom through the api the last_seen_ip of a user, Intercom will update all the fields related to location_data?

**Comment by dehora** [comment]
Essentially yes, but there are some limitations described in the faq item here: http://docs.intercom.io/FAQs/how-does-Intercom-get-my-users-location
