### ISSUE TITLE
Missing User.setLocationData(LocationData)

### ISSUE THREAD

**Issue by mgerner** [intercom/intercom-java#57]
Using version 1.1.0, there doesn't seem to be any method for adding location data to a user.

![screen shot 2015-05-12 at 10 40 51](https://cloud.githubusercontent.com/assets/995315/7584168/6a410a1e-f893-11e4-94dd-974298e656eb.png)

**Comment by dehora** [comment]
@mgerner that's intentional. A user's location data is computed by the servers, so the HTTP API doesn't provide a way to set it currently.

**Comment by mgerner** [comment]
Sorry - I just saw that this is a duplicate of https://github.com/intercom/intercom-java/issues/50 . Feel free to close.

**Comment by dehora** [comment]
@mgerner good of you to check, thanks!
