### ISSUE TITLE
Cannot remove users from Company

### ISSUE THREAD

**Issue by LeoIannacone** [intercom/intercom-java#70]
It's written in [intercom doc](https://doc.intercom.io/api/#companies-and-users):
```
To remove a company from a user add the field remove with a value of true
to the embedded company object and submit the user as a update request. 
You must also submit the id of the company.
```

Seems this operation is not possible with this library.

**Comment by dehora** [comment]
Thanks for that @LeoIannacone. There's a beta release here https://bintray.com/intercom/intercom-maven/intercom-java/1.3.0-b2/view that has support for removing companies  `removeCompany(Company company)` on the `User` if you want to give that a try.

**Comment by LeoIannacone** [comment]
Thanks for being so responsive.

I tried it, but seems nothing changed in the request. The debug log still show only this info for company in user:
```
...
companies: [{
    "name" : "My Cmp",
    "company_id" : "random ID"
  }]
...
```

According with the doc, both the "id" and the "remove" field should be passed.

**Comment by dehora** [comment]
@LeoIannacone I'm only able to replicate non-removal so far if the user object is submitted to API with a company that is in the list twice, as both an add and remove. Can you put a gist together showing the sequence of calls you're making?

**Comment by LeoIannacone** [comment]
I'm exactly doing what you do:
 - get the user via `User.find`
 - get the companies collection
 - check the difference between that list and the one I have in my db
 - remove companies if needed
 - update user

**Comment by broilogabriel** [comment]
I'm with the same problem here. Let's suppose I'm running the code below (Scala) for a company with only one user associated:

```scala
val user = User.find(Map("user_id" -> userId.toString).asJava)
val company = Company.find(Map("company_id" -> companyId.toString).asJava)
user.removeCompany(company)
val ret = User.update(user)
```
 
This code seems to work for the user, but if searched by the company again and and call the method getTotalCount it shows the user still associated and you'll be able to see the association in the app dashboard.

**Comment by mmartinic** [comment]
should be fixed with https://github.com/intercom/intercom-java/pull/124
