### ISSUE TITLE
Cannot create custom attribute of type date

### ISSUE THREAD

**Issue by rafaelfelini** [intercom/intercom-java#73]
Is there a way to create a date custom attribute?

I looked throughout ```io.intercom.api.CustomAttribute``` but not found nothing. Is there a way to handle that?

Thanks

**Comment by dehora** [comment]
@rafaelfelini there's no direct date type in the client at the moment, it's something we might look at in the future.

**Comment by Amelus** [comment]
Hi did anything change in the meantime?
On Intercom side there is a possibility to add custom attributes of type "Date" apparently
however there is no such thing in the SDK
I tried passing a timestamp as Long, but that shows "Invalid date" on Intercom side
how do I make use of that Dates?
