### ISSUE TITLE
Intercom is showing an error: E/Intercom-Android: ERROR: Api call failed: Canceled

### ISSUE THREAD

**Issue by EstebanSelaya** [intercom/intercom-java#75]
After making the following call using the Intercom-java framework:

Intercom.client().displayConversationsList();

A new activity opens up and shows an error message where normally a conversation list would be. "Unable to load conversations". Further, the logs show the following error: "E/Intercom-Android: ERROR: Api call failed: Canceled".

I'm unable to find any documentation to this specific error. Any help would be appreciated.

**Comment by DaleCantwell** [comment]
Hi @EstebanSelaya, sorry this is our java repo, here is a link to our issues for the Android integration https://github.com/intercom/intercom-android/issues
Would you mind opening this issue there and I'd be happy to help.

**Comment by EstebanSelaya** [comment]
Sure thing! https://github.com/intercom/intercom-android/issues/145
