### ISSUE TITLE
Usage of api client

### ISSUE THREAD

**Issue by cristianciutea** [intercom/intercom-java#76]
How should I use the api client. For example if I want to find a user by id, I do this:
User.find(id);
But from what I can tell, this call configures and registers a new jackson ObjectMapper module instance that is always the same. Why do we do this? I'm asking because I have a problem that after I do many api calls those objects remain stored in memory and the program stops with out of memory exception.

**Comment by dehora** [comment]
@cristianciutea thanks for reporting this. the loading was changed in #79 to stop reconfiguring the mapper, and is available in version 1.3.0-b3 if you want to give it a try.
