### ISSUE TITLE
Delete user is calling wrong url

### ISSUE THREAD

**Issue by aetheon** [intercom/intercom-java#77]
The delete user call is generating a 

```
DELETE https://api.intercom.io/users/{id}
```

instead of

```
DELETE https://api.intercom.io/users?user_id={id}
```

**Comment by dehora** [comment]
@aetheon The `/users/{id}` path is expected to work with the `id` of the user and not the `user_id`, (although that could be made a bit clearer). I'm also wondering if you were you looking for an option to delete by `user_id` (or `email`) from the client?

**Comment by aetheon** [comment]
Hi @dehora thanks for the quick reply. When I use the `user.id ` it works just fine ( I was using the `user_id` ).

BTW 'https://doc.intercom.io/api/#delete-a-user' was the url that fooled me. 

Thank you very much.

**Comment by dehora** [comment]
Thanks @aetheon - I'll see about getting the api doc updated to show the option.

**Comment by aetheon** [comment]
Cool. You guys are so awesome!

**Comment by dehora** [comment]
@aetheon we made a [small change to the delete user documentation](https://doc.intercom.io/api/#delete-a-user) based on this issue and I hope it makes things clearer. Once again thanks - making documentation better is a good thing and often under-appreciated.
