### ISSUE TITLE
Unrecognized field "metadata" exception

### ISSUE THREAD

**Issue by hjuskewycz** [intercom/intercom-java#78]
Hi,

I am using Intercom client

compile 'io.intercom:intercom-java:1.3.0-b2'

and when I try to read a webhook I get an exception. It looks like the field metadata is not recognized and also not defined in the class Notification.

```java
io.intercom.api.InvalidException: could not parse json string [Unrecognized field "metadata" (class io.intercom.api.Notification), not marked as ignorable (12 known properties: "data", "created_at", "first_sent_at", "self", "delivered_at", "topic", "delivery_attempts", "links", "app_id", "type", "id", "delivery_status"])
 at [Source: {
  "type" : "notification_event",
  "app_id" : "XXXXXX",
  "data" : {
    "type" : "notification_event_data",
    "item" : {
      "type" : "ping",
      "message" : "\"Usage is oxygen for ideas\" #interzen"
    }
  },
  "links" : { },
  "id" : null,
  "topic" : "ping",
  "delivery_status" : null,
  "delivery_attempts" : 1,
  "delivered_at" : 0,
  "first_sent_at" : 1447754089,
  "created_at" : 1447754089,
  "self" : null,
  "metadata" : { }
}; line: 20, column: 17] (through reference chain: io.intercom.api.Notification["metadata"])]
	at io.intercom.api.Notification.readJSON(Notification.java:20)
```

Can you please confirm this asap because of this is a bug I simply get the content myself.

**Comment by dehora** [comment]
@hjuskewycz thanks for reporting this. I'll take a look today.

**Comment by dehora** [comment]
@hjuskewycz the notification  published by the server was modified to remove the metadata field to allow `Notification.readJSON` client to consume the webhook data, which means webhooks you receive from here on  should be being marshalled ok by the client.

**Comment by hjuskewycz** [comment]
thanks for the info @dehora

**Comment by Dantee296** [comment]
@hemju @dehora Can u guy please tell how to receive Web-hooks ?
InputStream jsonStream = ...; **(how to receive here ?)**
final Notification notification = Notification.readJSON(jsonStream);
