### ISSUE TITLE
Adding a note to a conversation

### ISSUE THREAD

**Issue by floernoult** [intercom/intercom-java#81]
Hi,

I would like to be able to add a note to a given conversation. So it would mean, having a conversation, being able to manipulate the conversationPartCollection on it (to add notes in my case).
Is there any possibility to do this, or if not, any plan in the roadmap to add this feature?

Thanks a lot,
Florian

**Comment by bobjflong** [comment]
Hi @floernoult - can you try setting the message type to be `note`?

https://github.com/intercom/intercom-java#conversations
https://developers.intercom.io/docs/replying-to-a-conversation

**Comment by floernoult** [comment]
Great, it works fine! 
Thanks
