### ISSUE TITLE
bulk update crashes on response from server

### ISSUE THREAD

**Issue by kcech** [intercom/intercom-java#87]
Currently the server responds to the bulk submit like
```
{
  "app_id": "app_id",
  "id": "job_1234b123_12e1_11e5_8e6a_5f97e1eb8ad9",
  "created_at": 1449054998,
  "completed_at": null,
  "closing_at": 1449055898,
  "updated_at": 1449054998,
  "name": "api_bulk_job",
  "state": "running",
  "links": {
    "error": "https://api.intercom.io/jobs/job_1234b123_12e1_11e5_8e6a_5f97e1eb8ad9/error",
    "self": "https://api.intercom.io/jobs/job_1234b123_12e1_11e5_8e6a_5f97e1eb8ad9",
    "note": "You must authenticate with a valid API key to view these links."
  }
} 
```
The additional "note" in "links" is crashing the whole `User.submit()` method (line 187 in io.intercom.api.HttpClient), probably because a URI is expected.

**Comment by RuairiK** [comment]
Hi,

Sorry about this :(. I'm rolling back the server side change now. We'll fix the issue in this library then before rolling it back out.

Ruairí.

**Comment by kcech** [comment]
Yeah loosely typed language meets a strongly typed one :-) Thanks
