### ISSUE TITLE
Can iterate CompanyCollection returned by e.g. User.getCompanyCollection only once

### ISSUE THREAD

**Issue by prismec** [intercom/intercom-java#88]
This feels quite strange for a data object ? 

User user = new User()
user.addCompany(c1)
user.addCompany(c2)
assert user.getCompanyCollection() as List == [c1, c2]
assert user.getCompanyCollection() as List == []

**Comment by mmartinic** [comment]
Hi, `getCompanyCollection()` returns `CompanyCollection` that implements `Iterator<Company>` so you iterate over it that way if that is what you looking for.
