### ISSUE TITLE
Proguard rules?

### ISSUE THREAD

**Issue by fabiendem** [intercom/intercom-java#93]
Hello,

I am trying to integrate this library in an Android project but I need the Proguard rules if possible.

This is what I have so far:
```
# Intercom
-keep class intercom.** { *; }
-keep class org.slf4j.**
-dontwarn org.slf4j.**
-dontwarn org.w3c.dom.bootstrap.DOMImplementationRegistry
#-keep class org.apache.commons.codec.binary.**
-keep class org.apache.commons.** { *; }
-keep interface org.apache.commons.** { *; }

# Jackson 2
-keep class com.fasterxml.jackson.databind.ObjectMapper {
    public <methods>;
    protected <methods>;
}
-keep class com.fasterxml.jackson.databind.ObjectWriter {
    public ** writeValueAsString(**);
}
# Configuration for Guava 18.0
#
# disagrees with instructions provided by Guava project: https://code.google.com/p/guava-libraries/wiki/UsingProGuardWithGuava
-keep class com.google.common.io.Resources {
    public static <methods>;
}
-keep class com.google.common.collect.Lists {
    public static ** reverse(**);
}
-keep class com.google.common.base.Charsets {
    public static <fields>;
}

-keep class com.google.common.base.Joiner {
    public static com.google.common.base.Joiner on(java.lang.String);
    public ** join(...);
}

-keep class com.google.common.collect.MapMakerInternalMap$ReferenceEntry
-keep class com.google.common.cache.LocalCache$ReferenceEntry

# http://stackoverflow.com/questions/9120338/proguard-configuration-for-guava-with-obfuscation-and-optimization
-dontwarn javax.annotation.**
-dontwarn javax.inject.**
-dontwarn sun.misc.Unsafe

# Guava 19.0
-dontwarn java.lang.ClassValue
-dontwarn com.google.j2objc.annotations.Weak
-dontwarn org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement
```

But I am still getting an error during Runtime:
java.lang.NoSuchMethodError: No static method encodeBase64String([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/ext.jar)

Do you have any idea for me please?

**Comment by bobjflong** [comment]
Hey, @fabiendem

This library does not support Android. This is mostly because it uses full API keys that you would need to embed into your apps. Please check out the dedicated Android library: https://github.com/intercom/android-sdk

Alternatively, you could run intercom-java on your backend and proxy the requests (while providing your own auth).

**Comment by fabiendem** [comment]
Hello,

Thanks for the prompt reply!
I get a 404 for https://github.com/intercom/android-sdk
Do you mean https://github.com/intercom/intercom-android (limited to conversation list and message posting)?
I will probably use directly your REST Api instead of trying to get a wrapper!

Cheers
