### ISSUE TITLE
Resource Not Found

### ISSUE THREAD

**Issue by clicktravel-craig** [intercom/intercom-java#94]
I started using the Intercom API yesterday (intercom-java-1.3.1), I am simply using it to post admin conversations.

I have used it successfully to post many messages this morning, however now i'm getting a 404 Resource Not Found when I make a call to Conversation.create().

My code is posted below:

        Intercom.setAppID("...");
        Intercom.setApiKey("...");

        final User user = new User().setId("...");
        final Admin admin = new Admin().setId("...");
        final AdminMessage adminMessage = new AdminMessage().setAdmin(admin).setUser(user).setBody("...")
                .setMessageType("inapp").setTemplate("plain");
        Conversation.create(adminMessage);

As I stated this code has worked earlier today, however now it does not. Any assistance would be appreciated

Regards, Craig Handley (craig.handley@clicktravel.com)

**Comment by bobjflong** [comment]
Hi @clicktravel-craig could you double check that the user and admin already exist in Intercom with the ids you are specifying?

**Comment by clicktravel-craig** [comment]
Yes, I ran this code first to identify the users:

        final AdminCollection admins = Admin.list();
        while (admins.hasNext()) {
            final Admin admin = admins.next();
            System.out.println(admin.getName() + " : " + admin.getId() + " : " + admin.getEmail());
        }

        final UserCollection users = User.list();
        while (users.hasNext()) {
            final User user = users.next();

            if (user.getEmail() != null && user.getEmail().toLowerCase().contains("click")) {
                System.out.println(user.getName() + " : " + user.getId() + " : " + user.getEmail());
            }
        }

This code works correctly and does identify the user ids I can use

**Comment by clicktravel-craig** [comment]
The main strange thing is that the code was working correctly this morning but now is not

**Comment by bobjflong** [comment]
Hmm. would you mind getting in touch through the Intercom widget on the site and I'll take a look for you (just ask for Bob).
